# Site settings
title: Arthur Pachachura
email: pachachura.arthur@gmail.com
description: "Arthur Pachachura's Awesome Website"
url: "http://arthurpachachura.com/"
github_username:  smo-key

# Build settings
baseurl: ""
markdown: kramdown
permalink: /:title
relative_permalinks: false
highlighter: pygments
timezone: America/Chicago
lsi: true
