# Head settings
title: Arthur Pachachura
author: Arthur Pachachura
email: pachachura.arthur@gmail.com
description: "Arthur Pachachura's Website"
keywords: Arthur, Pachachura, Code, Developer, Designer

# Site settings
url: "http://arthurpachachura.com/"
github_username:  smo-key

# Build settings
#baseurl: ""
include: [".htaccess"]
permalink: /:title
relative_permalinks: false
highlighter: pygments
timezone: America/Chicago
lsi: true

# Syntax highlighter
markdown: kramdown
kramdown:
  input: GFM
